### PR TITLE
Patch to prevent the pc is undefined error on firefox 40+

### PR DESCRIPTION
**Pull request by madwill**
Following the comments on the reported issue number [#299](https://github.com/peers/peerjs/issues/299) this patch was taken from the ntt communication fork of peerjs and it prevent _makeOffer from crashing in a "pc is undefined" error in firefox. 

This error is critical and make communication in firefox unusable. 

Please consider.

### CODE REVIEW

**Comment by mingjunyang** [comment]
I use Firefox 43.0a2 (2015-10-23) Developer Edition, pc is undefined.

**Comment by hasanbostany** [comment]
I am using Firefox 43.0.1 and I get pc is undefined as well.
Is there anyway to have a look on conflict and apply the patch please?

**Comment by sir-isaac-newton** [comment]
+1 to @hasanbostany 

Any update on getting this merged?? I've been following this bug carefully for months now. The patch looks good to me. Please try to give this update a priority as it makes your awesome library virtually useless on Firefox! Thank you...

**Comment by madwill** [comment]
In the meantime... I've made this which is what i pull on the build server 

https://www.npmjs.com/package/peerjs_fork_firefox40

This is meant to be a temporary npm repo. to be removed once either this or someone else take on

**Comment by NerdsvilleCEO** [comment]
What is the process to get this in the upstream? I wouldn't mind volunteering :) This would help me out a lot

**Comment by sarbjeetsingh** [comment]
I am geting the same issue  pc is undefined how to rerolve this

**Comment by austinkelleher** [comment]
+1 I need this. cc @michelle @ericz

**Comment by sebenalern** [comment]
I am using firefox 45 and I am getting pc is undefined. How do I resolve this? I tried adding
the cdn from this website https://www.npmjs.com/package/peerjs_fork_firefox40. Thanks

**Comment by madwill** [comment]
@sebenalern

The readMe.md has not been changed, there is no CDN for this npm module. Please use npm to download dependency and link locally to the patched version. 

To this day i still use peerJs and i think its the best library out there. As long as we don't have to implement some of the new features like multi-streaming etc i will still use this library.

If a new blocker bug comes out and i can patch it i'll maintain as long as i can.

**Comment by sebenalern** [comment]
Sorry I am new to webRTC and a little inexperienced I am not sure what you mean by link locally. Could you please give a step by step set of instructions on how to fix the error?

**Comment by madwill** [comment]
This is more related to web development in general but either install NPM for your current OS of choice and launch: npm i peerjs_fork_firefox40

Or directly download the javascript file [here ](https://github.com/madwill/peerjs/tree/master/dist) and link them in your html page with a javascript link tag. 

<script defer src="peer.min.js"></script>

**Comment by maxenceC** [comment]
+1 @madwill Thanks for the fix, I'll use your npm module until the patch is officially merged

**Comment by rakotomandimby** [comment]
@madwill  , I forked peerjs to https://bitbucket.org/peerjsteam/peerjs and intend to receive some PR not merged yet. Would you please PR against https://bitbucket.org/peerjsteam/peerjs ? I will merge it quickly. As soon as some PR are merged, I'll re PR here waiting for the maintainers to get them.

**Comment by kidandcat** [comment]
Fixed in #419

**Pull request closed without merging**
