### PR TITLE
Added support for older chromium-based browsers

### PR DESCRIPTION
**Pull request by CodingSlime**

### CODE REVIEW

**Comment by rwrz** [comment]
why not just use webrtc-adapter (https://github.com/webrtchacks/adapter)?

**Comment by kidandcat** [comment]
PeerJS already uses webrtc-adapter, @CodingSlime could you tell us in which version of Chromium doesn't PeerJS works for you?

**Comment by CodingSlime** [comment]
I don't have the specific version but I tested it with UE 4 Browser and it didn't work with webrtc-adapter

**Comment by kidandcat** [comment]
UE 4 uses https://en.wikipedia.org/wiki/Chromium_Embedded_Framework

Idk which version so, I can't tell you if it supports webrtc or not

**Comment by afrokick** [comment]
@kidandcat we added it to dips, but didn't use)

I fixed it in https://github.com/peers/peerjs/pull/577

**Comment by CodingSlime** [comment]
@afrokick I just tested your PR and it works just fine with webrtc-adapter.

**Comment by afrokick** [comment]
@CodingSlime ok, I close this PR

**Pull request closed without merging**
