### PR TITLE
[WIP] V2.0.0

### PR DESCRIPTION
**Pull request by kidandcat**
# V2.0.0

- [ ] Connection metadata
- [ ] Max number of peers in a room
- [ ] Room password
- [ ] Disconnections
- [ ] Allow configurate custom MQTT server and TURN/STUN servers
- [ ] Test joining to multiple rooms
- [ ] Mute/unmute audio

### CODE REVIEW

**Comment by najibghadri** [comment]
Hello! Are these going to be merged sometimes?

**Comment by pspeter3** [comment]
Is this still the direction the project wants to go?

**Comment by antholeole** [comment]
Is this good to pull from? Some of these features are awesome.

**Comment by Taalaybek** [comment]
Will it be merged? Very nice features

**Pull request closed without merging**
