### PR TITLE
Add support for peer discovery .

### PR DESCRIPTION
**Pull request by macdasi**
Add an handle message of type 'discovery'

Other peers that connect to signal server will be able to config peer to be discovered by other connected peer , that way , other peer can register to .on('discovery', ... ) and get the new peer and connect to it .
this removes the needs to send the new peer by other means of exchange, such as opening another socket .

### CODE REVIEW

**Comment by macdasi** [comment]
It is linked to 
[peerjs-server pr99](https://github.com/peers/peerjs-server/pull/99)

**Comment by kidandcat** [comment]
Let me check other critical PRs and when I check the peer-server I will come back

**Comment by kidandcat** [comment]
What's the purpose of discovery? Could you show us a real world case?

Because in all common scenarios I have in mind, for example, a text chat, there will be a lot of users that it will not be performant for you to connect to everyone.

**Comment by kidandcat** [comment]
I'm closing this because lib has changed a lot since this PR. Anyway this looks like a nice feature to be implemented. I think there is already an issue describing this feature.

**Pull request closed without merging**
