### PR TITLE
Add WebRTC Adapter

### PR DESCRIPTION
**Pull request by capripio**

### CODE REVIEW

**Comment by kidandcat** [comment]
The README.md still points to your own Fork:
`npm install https://github.com/capripio/peerjs/tarball/master`

**Comment by capripio** [comment]
@kidandcat I've revert changes.

**Comment by kidandcat** [comment]
Thanks @capripio !!

**Comment by capripio** [comment]
@kidandcat  np!

**Comment by kalitine** [comment]
Is the adapter chipped along with `peerjs.min.js` v1.0.0 or should I added it myself as globals? Because  `src/adapter.ts` on the tag v1.0.0 is:
```typescript
import { adapter as _ } from "webrtc-adapter";

export const RTCSessionDescription =
  // @ts-ignore
  window.RTCSessionDescription || window.mozRTCSessionDescription;
export const RTCPeerConnection =
  // @ts-ignore
  window.RTCPeerConnection ||
  // @ts-ignore
  window.mozRTCPeerConnection ||
  // @ts-ignore
  window.webkitRTCPeerConnection;
export const RTCIceCandidate =
  // @ts-ignore
  window.RTCIceCandidate || window.mozRTCIceCandidate;
```
So actually the `webrtc-adapter` is not used at all and looking at `peerjs.min.js` there is 2 places where we have: `...require("./adapter")...`.

**Pull request merged**
