### PR TITLE
Switch from parcel to webpack

### PR DESCRIPTION
**Pull request by qpwo**
The parcelrequire stuff was causing problems in my package, and esbuild doesn't support ES5 output (#884). Tests seem to pass. Only thing is there might be more `addIceCandidate` warnings than before, maybe that has to with the shims (webrtc-adapter)?

screenshot

### CODE REVIEW

**Comment by pspeter3** [comment]
Parcel 2 is out now, maybe that would help? Additionally, I wonder if we could actually use ESbuild for the bundling.

**Comment by qpwo** [comment]
What about the lack of es5 support?

**Comment by pspeter3** [comment]
You're right, I totally missed that. I'm not sure what not supporting ES5 means in this context though.

**Comment by pspeter3** [comment]
Oh, I see what you're saying. Peer is using the TypeScript compiler to down level for ES5. I wonder if supporting ES5 is worth it though anymore?

**Comment by afrokick** [comment]
Seems like es6 is good choice for 2022 years(es6 was introduced 6 years ago). You can build es5 from sources without any problem.

And yeah, we will use ESBuild)

**Pull request closed without merging**
