### PR TITLE
Temasys AdapterJS integration with peerjs

### PR DESCRIPTION
**Pull request by letchoo**
This pull-request allows peerjs to be integrated with [Temasys's AdapterJS](https://github.com/Temasys/AdapterJS).

PeerJS issue: #216 
Temasys AdapterJS issue: [#55](https://github.com/Temasys/AdapterJS/issues/55)

Tested AdapterJS version: 0.10.6
Tested PeerJS version: 0.3.14

Tested example: adapterjs-integration (based off videochat example)
#### Test results

| Offerer \ Answerer | Safari v8.05 | IE v11 | Chrome v42 | Firefox v38 | Opera v29 |
| --- | --- | --- | --- | --- | --- |
| Opera v29 | Pass | - | Pass | Pass | Pass |
| Chrome v42 | Pass | Remote video not appearing in IE | Pass | #286 | Pass |
| Firefox v38 | Pass | Remote video not appearing in IE | #286 | Pass | Pass |
| Safari v8.05 | - | - | - | Pass | - |
| IE v11 | - | - | - | IE Crashes | #286 |

In all cases, getUserMedia works. All peers ICE candidates generated from each end has been added.

In all the failed cases (-), it means that remote video is not received in both peers.

### CODE REVIEW

**Comment by antonioaguilar** [comment]
Hi Michelle, 
I'm interested in testing the Temasys Plugin with PeerJS. I checkout this pull request #285 and tested the code with the latest version of the Temasys plugin (0.12.1). I tested with Chrome -> Safari, Safari -> Opera and the video does not work. 
Can you tell me if the problem is in the plugin or in PeerJS? I can help with some testing if you point me in the right direction ;-)

**Comment by gunsline2** [comment]
Hi @antonioaguilar try to use the example of this commit https://github.com/letchoo/peerjs/commit/be1b93a2b5c98d08da0fe239ccf72bbcebbb5781

**Comment by kidandcat** [comment]
@antonioaguilar Would you like to test again? the public server was down so it probably didn't worked because of that. If you want to try again, set host: "peerjs.com"

**Comment by kidandcat** [comment]
@letchoo if you are interested in getting this merged, could you have a look on the merge conflicts?

**Comment by kidandcat** [comment]
No news for a long time

**Pull request closed without merging**
