### PR TITLE
WIP: Nodejs Support

### PR DESCRIPTION
**Pull request by NickCis**
This issue is related to #606 .

I'm trying to add NodeJs support. I've somehow been able to add a hackish nodejs support. Although, the patch provided on this pr _"works"_, it has some problems. The main issue is the way this library handles binary data, it heavily relies on the `Blob` data type which is not supported on node. This wip only allows using the `json` serializer.

As it was suggested on the [node js support issue](https://github.com/peers/peerjs/issues/606#issuecomment-631027503), it could be simpler to use _peer js_ just for sharing the signaling part and relying on [`simple-peer`](https://github.com/feross/simple-peer) for all the web rtc stuff. This would require major changes on the library which I really don't know if the current maintainers would allow to be done.

That is why, before starting to code, I would like to have just a few thoughts of the maintainers. Perhaps, it would be preferable to start a new library (eg.: `simple-peerjs`) which uses the peerjs server in order to do the signal exchange and then delegates websocket to `simple-peer`. As this library will be heavily coupled to the peerjs server interface (and service), I think that it should partly maintained (or acknowledged) by the same organization. 

---
(Before running the example, the project has to be built `npm run build-nonminified`).

Example:
```js
const fetch = require('node-fetch');
const WebSocket = require('ws');
const Peer = require('./dist/peerjs').default;
const wrtc = require('wrtc');

global.RTCPeerConnection = wrtc.RTCPeerConnection;
global.RTCSessionDescription = wrtc.RTCSessionDescription;
global.RTCIceCandidate = wrtc.RTCIceCandidate;
global.fetch = fetch;
global.WebSocket = WebSocket;

const peer = new Peer({
  debug: 3,
});

peer.on('open', id => {
  console.log('Server peer id:', id);
});

peer.on('connection', conn => {
  conn.on('data', data => {
    console.log('server:', data);
  });

  conn.on('open', () => {
    conn.send('hello!');
  });
});
```

```js
const fetch = require('node-fetch');
const WebSocket = require('ws');
const Peer = require('./dist/peerjs').default;
const wrtc = require('wrtc');

global.RTCPeerConnection = wrtc.RTCPeerConnection;
global.RTCSessionDescription = wrtc.RTCSessionDescription;
global.RTCIceCandidate = wrtc.RTCIceCandidate;
global.fetch = fetch;
global.WebSocket = WebSocket;

const peer = new Peer({
  debug: 3,
});

peer.on('open', id => {
  console.log('Client peer id:', id);
  const conn = peer.connect('CONNECTION ID', { serialization: 'json'});

  conn.on('open', () => {
    console.log('connection open');
    setInterval(() => {
      conn.send('hi!');
    }, 1000);

    conn.on('data', (data) => {
      console.log('client:', data);
    });
  });
});
```

### CODE REVIEW

**Comment by NickCis** [comment]
For anyone interested I've started building a prototype of [`simple-peerjs`](https://github.com/nickcis/simple-peerjs) (uses exchange signaling by the _PeerJs_ protocol and then uses `simple-peer`). Currently, it is works, it lacks the stream implementation.

**Comment by HyperClockUp** [comment]
does it supports streaming transfer now? i want to create a peerjs instance in my node application so that make stream download realizable. so any suggestion can help me? thx a lot!!

**Comment by afrokick** [comment]
@NickCis sorry for the long delay. I think we can give it another life with v2. Do you have any issues which blocks this PR?

**Comment by afrokick** [comment]
Lets continue in https://github.com/peers/peerjs/pull/928

**Comment by NickCis** [comment]
> @NickCis sorry for the long delay. I think we can give it another life with v2. Do you have any issues which blocks this PR?

No problem!, Glad you've finally implemented a solution to this issue! :clap: :clap:

**Pull request closed without merging**
